typography_spectrum: 0.7905377394054085
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0062376519199460745
  lightness: 0.14411699259653687
  saturation: 0.5868686952162534
  rhythmicContrast: 0.7570294893812388
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2775807960424572
analytics:
  google: null
  facebook: null
  twitter: null
name: Marco's News
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: NOS Pricing
    url: >-
      https://docs.google.com/spreadsheets/d/10y8cErOgSclJdbBUB3F_Y_IDso1RAJZOZ4j1YVHj6Qw/pubhtml?gid=0&single=true
    type: external
favicon: null
title: TEST
purpose: []
